### ISSUE TITLE
Ignoring packages ?

### ISSUE THREAD

**Issue by WaynGames** [NormandErwan/DocFxForUnity#13]
Hi, 

I'm trying to setup documentation on my porject and follwoed the readme.
When I execute the command I get tons of warnings like this.

```
[20-05-15 11:43:57.232]Warning:[MetadataCommand.ExtractMetadata]Workspace failed with: [Failure] Le fichier 'C:\Users\\%USER%\Documents\GitHub\MGM\Packages\com.unity.test-framework\UnityEngine.TestRunner\TestRunner\TestListenerWrapper.cs' est introuvable.
```

I suppose it's trying to generated the documentation for the packages imported through the package manager.

How can I avoid this ?

**Comment by WaynGames** [comment]
"Fixed" by changing the docfx.json config like so :

```
 "metadata": [
        {
            "src": [
                {
                    "src": "../Assets",
                    "files": [ "**.cs" ]
                }
            ],
            "globalNamespaceId": "Global",
            "filter": "filterConfig.yml",
            "dest": "api"
        }
    ]
```

**Comment by NormandErwan** [comment]
I'm not sure what the problem was but I feel adding the `filterConfig.yml` was the solution. 

Please feel free to reopen the issue!
