### ISSUE TITLE
Unable to use DocFx on Unity

### ISSUE THREAD

**Issue by EricBatlle** [NormandErwan/DocFxForUnity#9]
Hi, following your README instructions I can display some Scripting API site if I use your own repo.

But if I try to make the same steps on a new project (empty for the exception of 1 .cs script) that is not uploaded on github I get the following errors: 
![image](https://user-images.githubusercontent.com/15261880/71646359-93fb2a00-2ce7-11ea-8974-f8811d8a4fdc.png)

I let the docfx.json exactly like yours and filterConfig.yml looks like:
![image](https://user-images.githubusercontent.com/15261880/71646366-b1c88f00-2ce7-11ea-99f6-c5d9f9f0990d.png)

Apparently seems to have one problem trying to create/find api folder, how can I solve this?

Thanks!

**Comment by NormandErwan** [comment]
If you want to include all C# scripts, you can go simpler by removing this line on your `Documentation/docfx.json`:

```diff
{
  "metadata": [
    {
      ...
-     "filter": "filterConfig.yml",
      "dest": "api/"
    }
  ],
  ...
}
```

Have you generated the `.csproj` files with Unity? DocFX is using them to generate the docs. On Unity, click [`Asset > Open C# Project`](https://docs.microsoft.com/fr-fr/visualstudio/cross-platform/media/vstu_open-csharp-project.png?view=vs-2019) to generate them.

**Comment by EricBatlle** [comment]
Thanks for the JSON advice.

I've generated the .csproj as you said: 
![image](https://user-images.githubusercontent.com/15261880/72221575-84d47180-355c-11ea-9e83-815949d3f3aa.png)

But the documentation still not works :S
![image](https://user-images.githubusercontent.com/15261880/72221600-b51c1000-355c-11ea-908f-a45be844d4de.png)

**Comment by NormandErwan** [comment]
I think it's related to Powershell. Can you try the same commands on Git bash, if you have installed it?

Meanwhile, I'm going to find a solution to be able to use DocFx with Powershell.

**Comment by EricBatlle** [comment]
Sorry for the big delay Normand, and thanks for still helping me.

I try the same with GitBash and the output was this: 
![image](https://user-images.githubusercontent.com/15261880/73590791-ce263a00-44e6-11ea-9258-2e166b3f6d96.png)

So the problem stills, basically the website generated on localhost have a non-interactable **Script API** button :( what's next?

**Comment by NormandErwan** [comment]
Can you try this command: `docfx metadata --force Documentation/docfx.json`?

DocFX works in two steps: first it extracts your source code data (the `metadata` subcomnand), then it generates the documentation website (the `build` subcommand). The bug here is related to the metadata step. I want to try to force it extract metadata from scratch, not using its internal cache from previous time.

**Comment by EricBatlle** [comment]
Ofc, here's the result:

![image](https://user-images.githubusercontent.com/15261880/73591019-bb613480-44e9-11ea-87f7-4b7ee763d7a4.png)

**Comment by NormandErwan** [comment]
That would be too easy! We're gonna find :)

What's the content of `metadata` in your `docfx.json`?

**Comment by EricBatlle** [comment]
Yei! That's the content!

![image](https://user-images.githubusercontent.com/15261880/73591085-77226400-44ea-11ea-8a2f-9d7410b3ca90.png)

**Comment by NormandErwan** [comment]
Can you add this line on your `docfx.json`:

```diff
     "metadata": [
         {
             "src": [
                 {
                     "src": "..",
                     "files": [ "**.csproj" ]
                 }
             ],
+            "globalNamespaceId": "Global",
             "dest": "api"
         }
     ],
```

It seems DocFX requires a namespace on all scripts. A default namespace can be attributed on scripts with `metadata.globalNamespaceId`: <https://github.com/dotnet/docfx/pull/1525>.

**Comment by EricBatlle** [comment]
I try the same adding this new line on the metadata field, but the Script API button still doesn't work :(
Could be that the "Global" name could be case-sensitive?
Edit: nope, that's not the problem, I've tried ^^'

Edit2: Added img if it helps
![image](https://user-images.githubusercontent.com/15261880/73607249-fb8ce980-45b3-11ea-8d9d-11ffdbe53aec.png)

**Comment by NormandErwan** [comment]
I don't get it :( Can you send me a zip of your project? I will try on my machine.
Meanwhile, I'm digging into DocFX's issues to find hints on this bug.

**Comment by ls29322** [comment]
I've sent the project to your github e-mail address!

**Comment by EricBatlle** [comment]
Absolutly, here is the project: https://mega.nz/#!TtZ3SaAY

**Comment by timower** [comment]
I have the same problem on MacOS, I've tried creating assembly definitions but still no luck :(
It would be nice if DocFX had more logging to debug the problem.

**Comment by NormandErwan** [comment]
Sorry, I'm late. @ls29322 I can't download it: a password is required.

@timower I agree, it lacks debug information! It's hard to tell why it fails.

**Comment by EricBatlle** [comment]
Uops, sorry @NormandErwan , link incomplete, here's the correct one: https://mega.nz/#!TtZ3SaAY!5XGr0bTMer5cen-ktS8y2bKpZB49pfuFPADfSVBx8tc

**Comment by NormandErwan** [comment]
I tried on my machine: after regenerating the C# projects with Unity (`Asset > Open C# Project`), DocFX generates all metadata.

Your `docfx.json` is correct and working. It seems on the DocFX issues there were frequent problems with the version of Visual Studio, [I understand DocFX is looking for specific version of VS](https://github.com/dotnet/docfx/issues/2265). I'm still digging to find a solution!

DocFX uses Visual Studio 2019 on my machine. I see its VS 2017 on your previous comments. You could download VS 2019 and try DocFX with it?

**Comment by NormandErwan** [comment]
@EricBatlle Have you tried with VS 2019? :)

**Comment by EricBatlle** [comment]
No sorry @NormandErwan , I've little (none) space on my disk and I can't download VS2019 ^^' But I don't forget this issue, I'll give you feedback when I try it :D

**Comment by NormandErwan** [comment]
I'm closing the issue. Feel free to comment if you try again, I'll re-open it!

**Comment by gnuumpat** [comment]
Hello and sorry for coming back to such an old issue. It appears that I am unable to generate the documentation from my Unity project following along your README file. For some reason, in the `metadata` phase when docfx tries to compile the source files, it cannot find the Unity namespaces. I recon that I made a mistake somewhere, but were unable to identify it until now.

It doesn't matter if I do it with GitBash, PowerShell or the Command Prompt and I also tried to regenerate my Visual Studio files by deleting it all and then press Assets > Open C# Project in Unity. 

Other than that, I use Unity Editor 2022.3.1f1.

Did anyone encounter a similar problem?

**Comment by MickDmnts** [comment]
@gnuumpat  Here for the same reason, trying some things around, I'll notify this post in case I find a workaround.

**Comment by David624634** [comment]
I had the same issue as @gnuumpat, and what worked for me was using DoxFx Version 2.61.0 instead of the newest version.

**Comment by mingyu243** [comment]
WOW!!! @David624634  thank you... my docfx version is 2.73.2

```
error CS0246: The type or namespace name 'UnityEditor' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'UnityEngine' could not be found (are you missing a using directive or an assembly reference?)
error CS0246: The type or namespace name 'MonoBehaviour' could not be found (are you missing a using directive or an assembly reference?)
```

dotnet tool uninstall -g docfx
dotnet tool install -g docfx --version 2.61.0

Now is working... thank you!!!

**Comment by kurone-kito** [comment]
Certainly, DocFX 2.61.0 works well for me.

As for 2.62.0 or later not working correctly, I thought that was due to dotnet/docfx#8399, but I don't know how to work around this breaking change in newer versions.

**Comment by fsedarkalex** [comment]
And even worse, docFX 2.61 seems to not work with VS 2019, or did anyone manage to get it running?
Doesn't find MSBuild here

**Comment by DSOE1024** [comment]
> 您好，很抱歉回到这样一个老问题。看来我无法按照您的 README 文件从我的 Unity 项目生成文档。由于某种原因，在 docfx 尝试编译源文件的阶段，它找不到 Unity 命名空间。我承认我在某个地方犯了一个错误，但直到现在都无法识别它。`metadata`
> 
> 不管我是使用 GitBash、PowerShell 还是命令提示符来执行此操作，我还尝试通过删除所有文件来重新生成我的 Visual Studio 文件，然后按 Assets >在 Unity 中打开 C# 项目。
> 
> 除此之外，我使用 Unity 编辑器 2022.3.1f1。
> 
> 有没有人遇到过类似的问题？

Yes, I'm having the same issue

**Comment by cheese3660** [comment]
I don't like to necro such an old issue, but I ran into this issue myself, and downgrading to docFX 2.61.0 has me run into another error where it is unable to extract the metadata.

```
Error extracting metadata for ... (multiple hundred files ellided by me)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolFormatter.SyntaxFormatter.AddTypedConstant(TypedConstant typedConstant) in /_/src/Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn/SymbolFormatter.Syntax.cs:line 320
...
```

**Comment by xk0fe** [comment]
@cheese3660 please try adding `"allowCompilationErrors": true` to metadata following this thread: https://github.com/dotnet/docfx/issues/9675#issuecomment-1921703926
